version: '3'
name: myproject
services:
  mysql:
    image: mysql:latest
    container_name: local_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
  
  zookeeper:
    image: zookeeper:latest
    container_name: local_zookeeper
    ports:
      - "2181:2181"

  redis:
    image: redis:latest
    container_name: local_redis
    ports:
      - "6379:6379"
